### ISSUE TITLE
Send pre-event email

### ISSUE THREAD

**Issue by RealEstateCafe** [FutureCommerce/Hackathon-Projects#4]
That means you Dazza

**Comment by RealEstateCafe** [comment]
Welcome Bill,

The organizers have added you to the list of Attendees at OnlineHackathon.com. Sign in and get free access to the official:

• Agenda Builder to create a schedule, save to your phone and share. 
• Friend Finder to see your Facebook and Twitter friends. 
• Social Directory to network and meet people ahead of time.

**Comment by dazzaji** [comment]
Bill - how does this look to you?

You are registered and we have a place for you at the FutureCommerce Hackathon and Unconference starting tomorrow at 1pm Eastern in-person at the MIT Media Lab and online at FutureCommerce.CIVICS.com/live  
- Important: Activate Your Account at OnlineHackathon2015.sched.org

To participate in-person or online, please take a moment to activate your account at OnlineHackathon2015.sched.org.  This account is integrated with a set of OnlineHackathon.com tools that will provide you simpler, faster and we believe more effective and fun ways to learn, engage in and even propose topics and sessions at our Unconference tomorrow and during the hackathon on Saturday and Sunday.  To activate, just click the "Set Your Password and Get Started" link in a big green button in your welcome email (subject "You Are Attending OnlineHackathon.com"). 
- Update: Join Us Live at the Venture Cafe

Join David Shrier and Dazza Greenwood at the Venture Cafe for an event preview. FutureCommerce has a table and people on hand to discuss the event. If you are in Cambridge, come to Venture Cafe at 1 Broadway, 5th Floor, Cambridge MA 02142 from 5:30-7:30pm November 19th!

For about 30 minutes between 7pm-8pm we will also go "live" on hangout as a way for our online event participants to join us. (live engagement tools are not yet available for use with this event unfortunately but you can begin using and enjoying these new ways to participate online starting tomorrow at 1:30 pm Eastern)
- Please don't hesitate to pose questions or ideas through our event site at FutureCommerce.CIVICS.com or if you have an urgent matter, please pull an issue ticket here (https://github.com/FutureCommerce/Hackathon-Projects/issues/new) and somebody on our organizing team can work on it even more quickly.

Looking forward to collaborating with you all tomorrow and beyond!

Cheers,
- Dazza Greenwood

**Comment by dazzaji** [comment]
DONE!
